apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: python-lnexiwlh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-lnexiwlh 
  name: python-lnexiwlh
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: python-lnexiwlh 
